# Generated by Django 2.2.4 on 2019-11-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, verbose_name='title')),
                ('content', models.CharField(blank=True, max_length=5000, verbose_name='content')),
                ('url', models.CharField(blank=True, error_messages={'unique': 'A URL already exists.'}, max_length=250, unique=True, verbose_name='url')),
                ('date', models.CharField(blank=True, max_length=30, verbose_name='date')),
                ('category', models.CharField(blank=True, max_length=150, verbose_name='category')),
                ('hashed', models.CharField(blank=True, max_length=254, verbose_name='hashed')),
                ('customer_type', models.CharField(blank=True, default='individual', max_length=150, null=True)),
                ('crawled', models.BooleanField(default=False, verbose_name='crawled')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('image_url', models.CharField(blank=True, error_messages={'unique': 'A URL already exists.'}, max_length=250, verbose_name='image_url')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
