# Generated by Django 2.2.4 on 2019-11-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listoverview',
            name='customer_type',
        ),
        migrations.AddField(
            model_name='listoverview',
            name='page',
            field=models.CharField(blank=True, max_length=254, verbose_name='page'),
        ),
        migrations.AddField(
            model_name='listoverview',
            name='page_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='page_number'),
        ),
        migrations.AlterField(
            model_name='listoverview',
            name='category',
            field=models.CharField(blank=True, max_length=500, verbose_name='category'),
        ),
    ]
